apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
        - name: dvwa
          image: citizenstig/dvwa:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: vnc
spec:
  replicas: 2
  selector:
    app: vnc
  template:
    metadata:
      labels:
        app: vnc
    spec:
      containers:
        - name: vnc
          image: dorowu/ubuntu-desktop-lxde-vnc:xenial
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vnc
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32333
  selector:
    app: vnc
  type: NodePort
