apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnc
  template:
    metadata:
      labels:
        app: vnc
    spec:
      containers:
        - name: vnc
          image: dorowu/ubuntu-desktop-lxde-vnc:xenial
          ports:
            - containerPort: 80