apiVersion: v1
kind: ReplicationController
metadata:
  name: vnc
spec:
  replicas: 2
  selector:
    app: vnc
  template:
    metadata:
      labels:
        app: vnc
    spec:
      containers:
        - name: vnc
          image: dorowu/ubuntu-desktop-lxde-vnc:xenial
          ports:
            - containerPort: 80